---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`push`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`delete`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`include?`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`size`"
  checked: true
name: Set o no set
