---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`push`"
  checked: true
- value: "`delete`"
  checked: true
- value: "`include?`"
  checked: true
- value: "`size`"
  checked: true
name: Set o no set
